/**
 * Centralized mapping of country names to high-quality flag URLs (FlagCDN)
 */
export const FLAG_MAPPING: Record<string, string> = {
  // Common / Prioritized
  nigeria: "https://flagcdn.com/w640/ng.png",
  italy: "https://flagcdn.com/w640/it.png",
  argentina: "https://flagcdn.com/w640/ar.png",
  brazil: "https://flagcdn.com/w640/br.png",
  france: "https://flagcdn.com/w640/fr.png",
  england: "https://flagcdn.com/w640/gb-eng.png",
  usa: "https://flagcdn.com/w640/us.png",
  germany: "https://flagcdn.com/w640/de.png",
  spain: "https://flagcdn.com/w640/es.png",
  portugal: "https://flagcdn.com/w640/pt.png",
  mexico: "https://flagcdn.com/w640/mx.png",
  canada: "https://flagcdn.com/w640/ca.png",
  morocco: "https://flagcdn.com/w640/ma.png",
  japan: "https://flagcdn.com/w640/jp.png",
  "south korea": "https://flagcdn.com/w640/kr.png",
  
  // Auto-populated from FlagCDN codes
  "andorra": "https://flagcdn.com/w640/ad.png",
  "united arab emirates": "https://flagcdn.com/w640/ae.png",
  "afghanistan": "https://flagcdn.com/w640/af.png",
  "antigua and barbuda": "https://flagcdn.com/w640/ag.png",
  "anguilla": "https://flagcdn.com/w640/ai.png",
  "albania": "https://flagcdn.com/w640/al.png",
  "armenia": "https://flagcdn.com/w640/am.png",
  "angola": "https://flagcdn.com/w640/ao.png",
  "antarctica": "https://flagcdn.com/w640/aq.png",
  "american samoa": "https://flagcdn.com/w640/as.png",
  "austria": "https://flagcdn.com/w640/at.png",
  "australia": "https://flagcdn.com/w640/au.png",
  "aruba": "https://flagcdn.com/w640/aw.png",
  "aland islands": "https://flagcdn.com/w640/ax.png",
  "azerbaijan": "https://flagcdn.com/w640/az.png",
  "bosnia and herzegovina": "https://flagcdn.com/w640/ba.png",
  "barbados": "https://flagcdn.com/w640/bb.png",
  "bangladesh": "https://flagcdn.com/w640/bd.png",
  "belgium": "https://flagcdn.com/w640/be.png",
  "burkina faso": "https://flagcdn.com/w640/bf.png",
  "bulgaria": "https://flagcdn.com/w640/bg.png",
  "bahrain": "https://flagcdn.com/w640/bh.png",
  "burundi": "https://flagcdn.com/w640/bi.png",
  "benin": "https://flagcdn.com/w640/bj.png",
  "saint barthelemy": "https://flagcdn.com/w640/bl.png",
  "bermuda": "https://flagcdn.com/w640/bm.png",
  "brunei": "https://flagcdn.com/w640/bn.png",
  "bolivia": "https://flagcdn.com/w640/bo.png",
  "caribbean netherlands": "https://flagcdn.com/w640/bq.png",
  "bahamas": "https://flagcdn.com/w640/bs.png",
  "bhutan": "https://flagcdn.com/w640/bt.png",
  "bouvet island": "https://flagcdn.com/w640/bv.png",
  "botswana": "https://flagcdn.com/w640/bw.png",
  "belarus": "https://flagcdn.com/w640/by.png",
  "belize": "https://flagcdn.com/w640/bz.png",
  "cocos (keeling) islands": "https://flagcdn.com/w640/cc.png",
  "dr congo": "https://flagcdn.com/w640/cd.png",
  "central african republic": "https://flagcdn.com/w640/cf.png",
  "republic of the congo": "https://flagcdn.com/w640/cg.png",
  "switzerland": "https://flagcdn.com/w640/ch.png",
  "cote d'ivoire (ivory coast)": "https://flagcdn.com/w640/ci.png",
  "cook islands": "https://flagcdn.com/w640/ck.png",
  "chile": "https://flagcdn.com/w640/cl.png",
  "cameroon": "https://flagcdn.com/w640/cm.png",
  "china": "https://flagcdn.com/w640/cn.png",
  "colombia": "https://flagcdn.com/w640/co.png",
  "costa rica": "https://flagcdn.com/w640/cr.png",
  "cuba": "https://flagcdn.com/w640/cu.png",
  "cape verde": "https://flagcdn.com/w640/cv.png",
  "curacao": "https://flagcdn.com/w640/cw.png",
  "christmas island": "https://flagcdn.com/w640/cx.png",
  "cyprus": "https://flagcdn.com/w640/cy.png",
  "czechia": "https://flagcdn.com/w640/cz.png",
  "germany": "https://flagcdn.com/w640/de.png",
  "djibouti": "https://flagcdn.com/w640/dj.png",
  "denmark": "https://flagcdn.com/w640/dk.png",
  "dominica": "https://flagcdn.com/w640/dm.png",
  "dominican republic": "https://flagcdn.com/w640/do.png",
  "algeria": "https://flagcdn.com/w640/dz.png",
  "ecuador": "https://flagcdn.com/w640/ec.png",
  "estonia": "https://flagcdn.com/w640/ee.png",
  "egypt": "https://flagcdn.com/w640/eg.png",
  "western sahara": "https://flagcdn.com/w640/eh.png",
  "eritrea": "https://flagcdn.com/w640/er.png",
  "spain": "https://flagcdn.com/w640/es.png",
  "ethiopia": "https://flagcdn.com/w640/et.png",
  "european union": "https://flagcdn.com/w640/eu.png",
  "finland": "https://flagcdn.com/w640/fi.png",
  "fiji": "https://flagcdn.com/w640/fj.png",
  "falkland islands": "https://flagcdn.com/w640/fk.png",
  "micronesia": "https://flagcdn.com/w640/fm.png",
  "faroe islands": "https://flagcdn.com/w640/fo.png",
  "france": "https://flagcdn.com/w640/fr.png",
  "gabon": "https://flagcdn.com/w640/ga.png",
  "united kingdom": "https://flagcdn.com/w640/gb.png",
  "scotland": "https://flagcdn.com/w640/gb-sct.png",
  "wales": "https://flagcdn.com/w640/gb-wls.png",
  "grenada": "https://flagcdn.com/w640/gd.png",
  "georgia": "https://flagcdn.com/w640/ge.png",
  "french guiana": "https://flagcdn.com/w640/gf.png",
  "guernsey": "https://flagcdn.com/w640/gg.png",
  "ghana": "https://flagcdn.com/w640/gh.png",
  "gibraltar": "https://flagcdn.com/w640/gi.png",
  "greenland": "https://flagcdn.com/w640/gl.png",
  "gambia": "https://flagcdn.com/w640/gm.png",
  "guinea": "https://flagcdn.com/w640/gn.png",
  "guadeloupe": "https://flagcdn.com/w640/gp.png",
  "equatorial guinea": "https://flagcdn.com/w640/gq.png",
  "greece": "https://flagcdn.com/w640/gr.png",
  "south georgia": "https://flagcdn.com/w640/gs.png",
  "guatemala": "https://flagcdn.com/w640/gt.png",
  "guam": "https://flagcdn.com/w640/gu.png",
  "guinea-bissau": "https://flagcdn.com/w640/gw.png",
  "guyana": "https://flagcdn.com/w640/gy.png",
  "hong kong": "https://flagcdn.com/w640/hk.png",
  "heard island and mcdonald islands": "https://flagcdn.com/w640/hm.png",
  "honduras": "https://flagcdn.com/w640/hn.png",
  "croatia": "https://flagcdn.com/w640/hr.png",
  "haiti": "https://flagcdn.com/w640/ht.png",
  "hungary": "https://flagcdn.com/w640/hu.png",
  "indonesia": "https://flagcdn.com/w640/id.png",
  "ireland": "https://flagcdn.com/w640/ie.png",
  "israel": "https://flagcdn.com/w640/il.png",
  "isle of man": "https://flagcdn.com/w640/im.png",
  "india": "https://flagcdn.com/w640/in.png",
  "british indian ocean territory": "https://flagcdn.com/w640/io.png",
  "iraq": "https://flagcdn.com/w640/iq.png",
  "iran": "https://flagcdn.com/w640/ir.png",
  "iceland": "https://flagcdn.com/w640/is.png",
  "jersey": "https://flagcdn.com/w640/je.png",
  "jamaica": "https://flagcdn.com/w640/jm.png",
  "jordan": "https://flagcdn.com/w640/jo.png",
  "kenya": "https://flagcdn.com/w640/ke.png",
  "kyrgyzstan": "https://flagcdn.com/w640/kg.png",
  "cambodia": "https://flagcdn.com/w640/kh.png",
  "kiribati": "https://flagcdn.com/w640/ki.png",
  "comoros": "https://flagcdn.com/w640/km.png",
  "saint kitts and nevis": "https://flagcdn.com/w640/kn.png",
  "north korea": "https://flagcdn.com/w640/kp.png",
  "kuwait": "https://flagcdn.com/w640/kw.png",
  "cayman islands": "https://flagcdn.com/w640/ky.png",
  "kazakhstan": "https://flagcdn.com/w640/kz.png",
  "laos": "https://flagcdn.com/w640/la.png",
  "lebanon": "https://flagcdn.com/w640/lb.png",
  "saint lucia": "https://flagcdn.com/w640/lc.png",
  "liechtenstein": "https://flagcdn.com/w640/li.png",
  "sri lanka": "https://flagcdn.com/w640/lk.png",
  "liberia": "https://flagcdn.com/w640/lr.png",
  "lesotho": "https://flagcdn.com/w640/ls.png",
  "lithuania": "https://flagcdn.com/w640/lt.png",
  "luxembourg": "https://flagcdn.com/w640/lu.png",
  "latvia": "https://flagcdn.com/w640/lv.png",
  "libya": "https://flagcdn.com/w640/ly.png",
  "monaco": "https://flagcdn.com/w640/mc.png",
  "moldova": "https://flagcdn.com/w640/md.png",
  "montenegro": "https://flagcdn.com/w640/me.png",
  "saint martin": "https://flagcdn.com/w640/mf.png",
  "madagascar": "https://flagcdn.com/w640/mg.png",
  "marshall islands": "https://flagcdn.com/w640/mh.png",
  "north macedonia": "https://flagcdn.com/w640/mk.png",
  "mali": "https://flagcdn.com/w640/ml.png",
  "myanmar": "https://flagcdn.com/w640/mm.png",
  "mongolia": "https://flagcdn.com/w640/mn.png",
  "macau": "https://flagcdn.com/w640/mo.png",
  "northern mariana islands": "https://flagcdn.com/w640/mp.png",
  "martinique": "https://flagcdn.com/w640/mq.png",
  "mauritania": "https://flagcdn.com/w640/mr.png",
  "montserrat": "https://flagcdn.com/w640/ms.png",
  "malta": "https://flagcdn.com/w640/mt.png",
  "mauritius": "https://flagcdn.com/w640/mu.png",
  "maldives": "https://flagcdn.com/w640/mv.png",
  "malawi": "https://flagcdn.com/w640/mw.png",
  "malaysia": "https://flagcdn.com/w640/my.png",
  "mozambique": "https://flagcdn.com/w640/mz.png",
  "namibia": "https://flagcdn.com/w640/na.png",
  "new caledonia": "https://flagcdn.com/w640/nc.png",
  "niger": "https://flagcdn.com/w640/ne.png",
  "norfolk island": "https://flagcdn.com/w640/nf.png",
  "nicaragua": "https://flagcdn.com/w640/ni.png",
  "netherlands": "https://flagcdn.com/w640/nl.png",
  "norway": "https://flagcdn.com/w640/no.png",
  "nepal": "https://flagcdn.com/w640/np.png",
  "nauru": "https://flagcdn.com/w640/nr.png",
  "niue": "https://flagcdn.com/w640/nu.png",
  "new zealand": "https://flagcdn.com/w640/nz.png",
  "oman": "https://flagcdn.com/w640/om.png",
  "panama": "https://flagcdn.com/w640/pa.png",
  "peru": "https://flagcdn.com/w640/pe.png",
  "french polynesia": "https://flagcdn.com/w640/pf.png",
  "papua new guinea": "https://flagcdn.com/w640/pg.png",
  "philippines": "https://flagcdn.com/w640/ph.png",
  "pakistan": "https://flagcdn.com/w640/pk.png",
  "poland": "https://flagcdn.com/w640/pl.png",
  "saint pierre and miquelon": "https://flagcdn.com/w640/pm.png",
  "pitcairn islands": "https://flagcdn.com/w640/pn.png",
  "puerto rico": "https://flagcdn.com/w640/pr.png",
  "palestine": "https://flagcdn.com/w640/ps.png",
  "palau": "https://flagcdn.com/w640/pw.png",
  "paraguay": "https://flagcdn.com/w640/py.png",
  "qatar": "https://flagcdn.com/w640/qa.png",
  "reunion": "https://flagcdn.com/w640/re.png",
  "romania": "https://flagcdn.com/w640/ro.png",
  "serbia": "https://flagcdn.com/w640/rs.png",
  "russia": "https://flagcdn.com/w640/ru.png",
  "rwanda": "https://flagcdn.com/w640/rw.png",
  "saudi arabia": "https://flagcdn.com/w640/sa.png",
  "solomon islands": "https://flagcdn.com/w640/sb.png",
  "seychelles": "https://flagcdn.com/w640/sc.png",
  "sudan": "https://flagcdn.com/w640/sd.png",
  "sweden": "https://flagcdn.com/w640/se.png",
  "singapore": "https://flagcdn.com/w640/sg.png",
  "saint helena, ascension and tristan da cunha": "https://flagcdn.com/w640/sh.png",
  "slovenia": "https://flagcdn.com/w640/si.png",
  "svalbard and jan mayen": "https://flagcdn.com/w640/sj.png",
  "slovakia": "https://flagcdn.com/w640/sk.png",
  "sierra leone": "https://flagcdn.com/w640/sl.png",
  "san marino": "https://flagcdn.com/w640/sm.png",
  "senegal": "https://flagcdn.com/w640/sn.png",
  "somalia": "https://flagcdn.com/w640/so.png",
  "suriname": "https://flagcdn.com/w640/sr.png",
  "south sudan": "https://flagcdn.com/w640/ss.png",
  "sao tome and principe": "https://flagcdn.com/w640/st.png",
  "el salvador": "https://flagcdn.com/w640/sv.png",
  "sint maarten": "https://flagcdn.com/w640/sx.png",
  "syria": "https://flagcdn.com/w640/sy.png",
  "eswatini (swaziland)": "https://flagcdn.com/w640/sz.png",
  "turks and caicos islands": "https://flagcdn.com/w640/tc.png",
  "chad": "https://flagcdn.com/w640/td.png",
  "french southern and antarctic lands": "https://flagcdn.com/w640/tf.png",
  "togo": "https://flagcdn.com/w640/tg.png",
  "thailand": "https://flagcdn.com/w640/th.png",
  "tajikistan": "https://flagcdn.com/w640/tj.png",
  "tokelau": "https://flagcdn.com/w640/tk.png",
  "timor-leste": "https://flagcdn.com/w640/tl.png",
  "turkmenistan": "https://flagcdn.com/w640/tm.png",
  "tunisia": "https://flagcdn.com/w640/tn.png",
  "tonga": "https://flagcdn.com/w640/to.png",
  "turkey": "https://flagcdn.com/w640/tr.png",
  "trinidad and tobago": "https://flagcdn.com/w640/tt.png",
  "tuvalu": "https://flagcdn.com/w640/tv.png",
  "taiwan": "https://flagcdn.com/w640/tw.png",
  "tanzania": "https://flagcdn.com/w640/tz.png",
  "ukraine": "https://flagcdn.com/w640/ua.png",
  "uganda": "https://flagcdn.com/w640/ug.png",
  "united states minor outlying islands": "https://flagcdn.com/w640/um.png",
  "united nations": "https://flagcdn.com/w640/un.png",
  "united states": "https://flagcdn.com/w640/us.png",
  "uruguay": "https://flagcdn.com/w640/uy.png",
  "uzbekistan": "https://flagcdn.com/w640/uz.png",
  "vatican city (holy see)": "https://flagcdn.com/w640/va.png",
  "saint vincent and the grenadines": "https://flagcdn.com/w640/vc.png",
  "venezuela": "https://flagcdn.com/w640/ve.png",
  "british virgin islands": "https://flagcdn.com/w640/vg.png",
  "united states virgin islands": "https://flagcdn.com/w640/vi.png",
  "vietnam": "https://flagcdn.com/w640/vn.png",
  "vanuatu": "https://flagcdn.com/w640/vu.png",
  "wallis and futuna": "https://flagcdn.com/w640/wf.png",
  "samoa": "https://flagcdn.com/w640/ws.png",
  "kosovo": "https://flagcdn.com/w640/xk.png",
  "yemen": "https://flagcdn.com/w640/ye.png",
  "mayotte": "https://flagcdn.com/w640/yt.png",
  "south africa": "https://flagcdn.com/w640/za.png",
  "zambia": "https://flagcdn.com/w640/zm.png",
  "zimbabwe": "https://flagcdn.com/w640/zw.png"
};

/**
 * Returns a flag URL for a given country name, preferring the manual mapping
 */
export function getFlagUrl(countryName: string, apiFallback?: string): string {
  if (!countryName) return apiFallback || "/images/placeholder.png";
  
  const normalized = countryName.toLowerCase().trim();
  
  // 1. Check manual mapping for known high-quality flags
  if (FLAG_MAPPING[normalized]) {
    return FLAG_MAPPING[normalized];
  }
  
  // 2. Use API fallback if provided and looks valid
  if (apiFallback && apiFallback.startsWith('http')) {
    return apiFallback;
  }
  
  // 3. Final default placeholder
  return "/images/placeholder.png";
}
